## Anotações Tech Challenge

link: [http://vitibrasil.cnpuv.embrapa.br/index.php?opcao=opt_01]

O intuito desse markdown é fazer anotações sobre o formato e inconsistências encontradas nos arquivos para servir de documentação e de guia para o tratamento dos dados

In [15]:
import pandas as pd
import glob
import os

In [16]:
# Funções e variaveis usadas em varias celulas


def fn_consolida_arquivos(caminho, separador=";"):
    lst_arq_import = glob.glob(caminho)
    df_lista = []
    for f in lst_arq_import:
        df_tmp = pd.read_csv(f, sep=separador)
        df_tmp["nomeArquivo"] = os.path.basename(f)
        df_lista.append(df_tmp)
    return pd.concat(df_lista)

dic_continente = {
    "Afeganistão": "Ásia",
    "Alemanha": "Europa",
    "Argentina": "América do Sul",
    "Argélia": "África",
    "Armênia": "Ásia",
    "Arábia Saudita": "Ásia",
    "Austrália": "Oceania",
    "Bahamas": "América do Norte",
    "Bermudas": "América do Norte",
    "Bolívia": "América do Sul",
    "Brasil": "América do Sul",
    "Bulgária": "Europa",
    "Bélgica": "Europa",
    "Bósnia-Herzegovina": "Europa",
    "Canadá": "América do Norte",
    "Chile": "América do Sul",
    "China": "Ásia",
    "Cingapura": "Ásia",
    "Colômbia": "América do Sul",
    "Coreia do Norte": "Ásia",
    "Coreia do Sul": "Ásia",
    "Costa Rica": "América Central",
    "Croácia": "Europa",
    "Cuba": "América do Norte",
    "Dinamarca": "Europa",
    "Egito": "África",
    "Emirados Árabes Unidos": "Ásia",
    "Eslováquia": "Europa",
    "Eslovênia": "Europa",
    "Espanha": "Europa",
    "Estados Unidos": "América do Norte",
    "França": "Europa",
    "Geórgia": "Europa",
    "Grécia": "Europa",
    "Guiana": "América do Sul",
    "Hong Kong": "Ásia",
    "Hungria": "Europa",
    "Ilhas Geórgia do Sul e Sandwich do Sul": "Antártica",
    "Indonésia": "Ásia",
    "Irlanda": "Europa",
    "Irã": "Ásia",
    "Israel": "Ásia",
    "Itália": "Europa",
    "Iugoslavia": "Europa",
    "Japão": "Ásia",
    "Luxemburgo": "Europa",
    "Líbano": "Ásia",
    "Macedônia": "Europa",
    "Marrocos": "África",
    "Mexico": "América do Norte",
    "Moldávia": "Europa",
    "Montenegro": "Europa",
    "México": "América do Norte",
    "Noruega": "Europa",
    "Nova Zelândia": "Oceania",
    "Outros": "Outros",
    "Panama": "América Central",
    "Paraguai": "América do Sul",
    "Países Baixos": "Europa",
    "Peru": "América do Sul",
    "Porto Rico": "América do Norte",
    "Portugal": "Europa",
    "Reino Unido": "Europa",
    "Republica Dominicana": "América do Norte",
    "República Tcheca": "Europa",
    "Romênia": "Europa",
    "Rússia": "Europa",
    "San Marino": "Europa",
    "Suécia": "Europa",
    "Suíça": "Europa",
    "Sérvia": "Europa",
    "Síria": "Ásia",
    "Taiwan": "Ásia",
    "Tunísia": "África",
    "Turquia": "Europa",
    "Ucrânia": "Europa",
    "Uruguai": "América do Sul",
    "Uzbequistão": "Ásia",
    "Venezuela": "América do Sul",
    "África do Sul": "África",
    "Áustria": "Europa",
    "Índia": "Ásia",
}

# Corrigir nomes dos paises nos arquivos de importação e exportação
dic_pais = {
    "Africa do Sul": "África do Sul",
    "Alemanha, República Democrática": "Alemanha",
    "Alemanha, República Democrática da":"Alemanha",
    "Austria": "Áustria",
    "Bulgaria": "Bulgária",
    "Coreia do Sul, República": "Coreia do Sul",
    "Coreia do Norte, República": "Coreia do Norte",
    "Canada": "Canadá",
    "China Continental": "China",
    "Emirados": "Emirados Árabes Unidos",
    "Emirados Arabes Unidos": "Emirados Árabes Unidos",
    "Geórgia do Sul e Sandwich do Sul, Ilhas": "Ilhas Geórgia do Sul e Sandwich do Sul",
    "Grecia": "Grécia",
    "Guiana Britânica": "Guiana",
    "Não consta na tabela": "Outros",
    "Não declarados": "Outros",
    "Paises Baixos (Holanda)": "Países Baixos",
    "Paises Baixos": "Países Baixos",
    "Panamá": "Panama",
    "Romenia": "Romênia",
    "Tcheca, República": "República Tcheca",
    "Tunisia": "Tunísia",
    "itália": "Itália",
    "India": "Índia",
    "Iugoslávia": "Sérvia",
    "Iugoslâvia": "Sérvia",
    "Antigua e Barbuda": "Antígua e Barbuda",
    "Australia":"Austrália",
    "Cayman, Ilhas":"Ilhas Cayman",
    "Cocos (Keeling), Ilhas":"Ilhas Cocos (Keeling)",
    "Colombia":"Colômbia",
    "Coreia do Sul, Republica da":"Coreia do Sul",
    "Coreia, Republica Sul":"Coreia do Sul",
    "Coveite":"Kuwait",
    "Dominica, Ilha de":"Dominica",
    "Eslovaca, Republica":"Eslováquia",
    "Falkland (Ilhas Malvinas)":"Ilhas Malvinas",
    "Falkland (Malvinas)":"Ilhas Malvinas",
    "Faroé, Ilhas":"Ilhas Faroé",
    "Grêcia":"Grécia",
    "Guiné Bissau":"Guiné-Bissau",
    "Guine Bissau":"Guiné-Bissau",
    "Guine Equatorial":"Guiné Equatorial",
    "Indonêsia":"Indonésia",
    "Islandia":"Islândia",
    "Italia":"Itália",
    "Letonia":"Letônia",
    "Libêria":"Libéria",
    "Malasia":"Malásia",
    "Marshall, Ilhas":"Ilhas Marshall",
    "Mexico":"México",
    "Namibia":"Namíbia",
    "Nicaragua":"Nicarágua",
    "Nova Zelandia":"Nova Zelândia",
    "Outros(1)":"Outros",
    "Polonia":"Polônia",
    "Quenia":"Quênia",
    "Republica Tcheca":"República Tcheca",
    "República Federativa da Rússia":"Rússia",
    "Russia":"Rússia",
    "Russia,  Federação da":"Rússia",
    "Suecia":"Suécia",
    "São Tomé e Principe":"São Tomé e Príncipe",
    "Tailandia":"Tailândia",
    "Taiwan (FORMOSA)":"Taiwan",
    "Taiwan (Formosa)":"Taiwan",
    "Trindade e Tobago":"Trindade e Tobago",
    "Trinidade Tobago":"Trindade e Tobago",
    "Trinidade e Tobago":"Trindade e Tobago",
    "Turcas e Caicos, ilhas":"Ilhas Turcas e Caicos",
}

# Arquivo Produção.csv

- 51 linhas: descrição dos produtos
- 55 colunas: id/nome do produto e cada coluna com o volume produção por ano (1970-2022)

Inconsistências:

- Algumas linhas correspondem aos agrupamentos dos produtos, por exemplo id 1 (VINHO DE MESA), é o agrupamento dos ids 2 até 4, mesmo comportamento acontece nos IDs 5, 9 e 14
- Não temos valor para SUCOS entre 73 e 84, nesse mesmo período o valor de produção do mosto aumentou muito, como o mosto faz parte do processo de fabricação da uva, creio que acabou sendo contabilizado tudo junto. Acontece algo parecido com os ids 39 e 42
  "O mosto corresponde ao líquido extraído da uva, enquanto o suco de uva representa o mosto processado, isto é, submetido a determinadas práticas para auxiliar na extração da matéria corante e garantir a sua clarificação, estabilização e conservação até o momento do consumo." -> https://ainfo.cnptia.embrapa.br/digital/bitstream/item/198428/1/Metodologia-Analise-Mosto-Suco-Uva-ed01-2010.pdf

In [18]:
df_prod = pd.read_csv(r".\Arquivos\Producao.csv", sep=";")
# Excluir coluna id do arquivo
df_prod.drop(columns=["id"], inplace=True)

# Criar campo categoria
df_prod["categoria"] = ""
df_prod.loc[1:3, "categoria"] = "VINHO DE MESA"
df_prod.loc[5:7, "categoria"] = "VINHO FINO DE MESA (VINÍFERA)"
df_prod.loc[9:13, "categoria"] = "SUCO"
df_prod.loc[15:, "categoria"] = "DERIVADOS"

# Excluir linhas com valores acumulados
df_prod_filtro = df_prod.query(
    "produto not in ('VINHO DE MESA','VINHO FINO DE MESA (VINÍFERA)','SUCO','DERIVADOS')"
)

# Transpor colunas de anos em linhas
df_prod_melt = df_prod_filtro.melt(
    id_vars=["produto", "categoria"], var_name="Ano", value_name="quantidade_L"
)
df_prod_melt

,produto,categoria,Ano,quantidade_L
0,Tinto,VINHO DE MESA,1970,174224052
1,Branco,VINHO DE MESA,1970,748400
2,Rosado,VINHO DE MESA,1970,42236152
3,Tinto,VINHO FINO DE MESA (VINÍFERA),1970,7591557
4,Branco,VINHO FINO DE MESA (VINÍFERA),1970,15562889
...,...,...,...,...
2486,Espumante orgânico,DERIVADOS,2022,0
2487,Destilado alcoólico simples de bagaceira,DERIVADOS,2022,4300
2488,Vinho acidificado,DERIVADOS,2022,0
2489,Mosto parcialmente fermentado,DERIVADOS,2022,0
2490,Outros derivados,DERIVADOS,2022,247228

### Arquivos Importação

In [19]:
df = fn_consolida_arquivos(r".\Arquivos\Imp*.csv")
print(df.shape)

(194, 111)

In [20]:
# Ajustar colunas
dic_cat = {
    "ImpEspumantes.csv": "Espumantes",
    "ImpFrescas.csv": "Uvas frescas",
    "ImpPassas.csv": "Uvas passas",
    "ImpSuco.csv": "Suco",
    "ImpVinhos.csv": "Vinhos de mesa",
}

df["2022"].fillna(df["2021.2"], inplace=True)
df["2022.1"].fillna(df["2021.3"], inplace=True)
df["Categoria"] = df["nomeArquivo"].map(dic_cat)
df.drop(columns=["Id", "nomeArquivo", "2021.2", "2021.3"], inplace=True)

In [21]:
# Selecionar colunas de ano
lst_cols = [c for c in df.columns if c not in ["País", "Categoria"]]
# Renomear colunas de ano
lst_cols_rename = [
    c.replace(".1", "") + "_Valor" if "." in c else c + "_Peso" for c in lst_cols
]
# Renomear df
df.columns = [
    c if c not in lst_cols else lst_cols_rename[lst_cols.index(c)] for c in df.columns
]

In [22]:
df_imp_melt = df.melt(
    id_vars=["País", "Categoria"], var_name="Ano_Tipo", value_name="Valor"
)
df_imp_melt["Valor"].fillna(0, inplace=True)
df_imp_melt[["Ano", "Tipo"]] = df_imp_melt["Ano_Tipo"].str.split("_", expand=True)

In [23]:
df_imp_melt["País_aj"] = df_imp_melt["País"].map(dic_pais)
df_imp_melt["País"] = df_imp_melt["País_aj"].fillna(df_imp_melt["País"])
df_imp_melt.drop(columns=["Ano_Tipo", "País_aj"], inplace=True)
df_imp_melt = (
    df_imp_melt.groupby(by=["País", "Categoria", "Tipo", "Ano"])
    .agg({"Valor": "sum"})
    .reset_index()
)
df_imp_melt

              País    Categoria   Tipo   Ano      Valor
0      Afeganistão  Uvas passas   Peso  1970        0.0
1      Afeganistão  Uvas passas   Peso  1971        0.0
2      Afeganistão  Uvas passas   Peso  1972        0.0
3      Afeganistão  Uvas passas   Peso  1973        0.0
4      Afeganistão  Uvas passas   Peso  1974        0.0
...            ...          ...    ...   ...        ...
19817        Índia  Uvas passas  Valor  2018  1007031.0
19818        Índia  Uvas passas  Valor  2019   677056.0
19819        Índia  Uvas passas  Valor  2020   813317.0
19820        Índia  Uvas passas  Valor  2021   504532.0
19821        Índia  Uvas passas  Valor  2022  2568914.0

[19822 rows x 5 columns]

### Arquivos Exportação

In [24]:
df_exp = fn_consolida_arquivos(r".\Arquivos\Exp*.csv")
print(df_exp.shape)

(477, 109)

In [25]:
# Ajustar colunas
dic_cat = {
    "ExpEspumantes.csv": "Espumantes",
    "ExpUva.csv": "Uvas frescas",
    "ExpSuco.csv": "Suco",
    "ExpVinho.csv": "Vinhos de mesa",
}
df_exp["Categoria"] = df_exp["nomeArquivo"].map(dic_cat)
df_exp.drop(columns=["Id", "nomeArquivo"], inplace=True)

In [26]:
# Selecionar colunas de ano
lst_cols = [c for c in df_exp.columns if c not in ["País", "Categoria"]]
# Renomear colunas de ano
lst_cols_rename = [
    c.replace(".1", "") + "_Valor" if "." in c else c + "_Peso" for c in lst_cols
]
# Renomear df
df_exp.columns = [
    c if c not in lst_cols else lst_cols_rename[lst_cols.index(c)]
    for c in df_exp.columns
]

df_exp_melt = df_exp.melt(
    id_vars=["País", "Categoria"], var_name="Ano_Tipo", value_name="Valor"
)
df_exp_melt["Valor"].fillna(0, inplace=True)
df_exp_melt[["Ano", "Tipo"]] = df_exp_melt["Ano_Tipo"].str.split("_", expand=True)

df_exp_melt["País_aj"] = df_exp_melt["País"].map(dic_pais)
df_exp_melt["País"] = df_exp_melt["País_aj"].fillna(df_exp_melt["País"])
df_exp_melt.drop(columns=["Ano_Tipo", "País_aj"], inplace=True)
df_exp_melt = (
    df_exp_melt.groupby(by=["País", "Categoria", "Tipo", "Ano"])
    .agg({"Valor": "sum"})
    .reset_index()
)

In [27]:
## Exportar arquivos Tableau

caminho = f"C:\\Users\\{os.getlogin()}\\Documents\\Meu Repositório do Tableau\\Fontes de dados"

df_prod_melt.to_csv(caminho + r"\base_producao_oficial.csv", index=False, sep=";", decimal=",")
df_imp_melt.to_csv(caminho + r"\base_importacao.csv", index=False, sep=";", decimal=",")
df_exp_melt.to_csv(caminho + r"\base_exportacao.csv", index=False, sep=";", decimal=",")